[Source]
kubernetes_url = "https://kubernetes.default"

[EventsConfig]
enabled = true

[EventsConfig.KafkaEventConfig]
enabled = true
brokers = ["10.146.143.206:9092"]
topic = "heapster-events"
namespaces = ["default","lc"]
kinds = ["Pod", "Deployment","NameSpace"]

[DeleteInspectionConfig]
enabled = true
speed = 60

[DeleteInspectionConfig.KafkaDeleteConfig]
enabled = true
brokers = ["10.146.143.206:9092"]
topic = "heapster-deletes"
namespaces = ["lc","default"]
kinds = ["Pod"]

[NodeInspectionConfig]
enabled = true
speed = 60

[NodeInspectionConfig.KafkaNodeConfig]
enabled = true
brokers = ["10.146.143.206:9092"]
topic = "heapster-nodes"

[PodInspectionConfig]
enabled = true
speed = 60
timeout_threshold = 300

[PodInspectionConfig.KafkaPodConfig]
enabled = true
brokers = ["10.146.143.206:9092"]
topic = "heapster-pods"
namespaces = ["default","kube-system","lc"]
